# Generated by Django 6.0.1 on 2026-01-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(max_length=4, unique=True)),
                ('empname', models.CharField(max_length=30)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_ph', models.IntegerField(max_length=10, unique=True)),
                ('emp_job', models.CharField()),
                ('emp_sal', models.IntegerField()),
                ('emp_DOJ', models.DateField()),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
